### ISSUE TITLE
Package ITN orchestrator

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#15768]

**Comment by georgeee** [comment]
Related issue: https://app.zenhub.com/workspaces/platform-engineering-652fc5b78bd6b33584ffedf9/issues/zh/103

**Comment by georgeee** [comment]
**Services from docker compose files (using version 2)**

_Uptime backend_

```
  uptime-backend:
    image: gcr.io/o1labs-192920/delegation-backend:2.1.0
    container_name: uptime-backend
    restart: always
    ports:
      - 6000:8080
    volumes:
      - ./config:/config
    environment:
      NETWORK: testnet
      CONFIG_FILE: /config/conf.json
```

Where `conf.json` is the following, with public keys to be list of public keys corresponding to what we pass via `--uptime-submitter-key` to Mina nodes:

```
{
  "in_memory": true,
  "whitelist": [
    "B62qkasW9RRENzCzdEov1PRQ63BUT2VQK9iU7imcvbPLThnhL2eYMz8",
    "B62qp3x5osG6Fz6j44FVn61E4DNpAnyDEMcoQdNQZAdhaR7sj4wZ6gW",
    "B62qii4xfjQ3Vg5dsq7RakYTENQkdD8pFPMgqtUdC9FhgvBbwEbRoML"
  ]
}
```

_Internal log fetcher_

```
  internal-log-fetcher:
    image: gcr.io/o1labs-192920/mina-internal-trace-consumer:1.3.0
    container_name: internal-log-fetcher
    restart: always
    command: "fetcher -k /keys/secret_key -o /output --db-uri 'postgresql://postgres:secret_password_12345@postgres:5432' discovery"
    ports:
      - 4000:4000
      - 11000-11700:11000-11700
    volumes:
      - ./keys:/keys
      - ./output:/output
      - ./names-data:/names-data
    environment:
      INTERNAL_TRACE_CONSUMER_EXE: /internal_trace_consumer
      FETCH_INTERVAL_MS: 10000
      ONLINE_URL: "http://itn.openmina.com:6000/v1/online" # URL exposed by uptime-backend
```

_Postgresql instance_

Special configurations are passed to sustain simultaneous connections for log fetchers launched to support ~200 Mina nodes.

```
  postgres:
    image: postgres
    shm_size: 1g
    container_name: postgres
    restart: always
    ports:
      - 5455:5432
    command: "-c max_connections=10000 -c shared_buffers=2048MB"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: secret_password_12345
```

_VS dashboard (optional)_

For the initial version, let's skip it.

```
  frontend:
    image: directcuteo/mina-frontend:663f692
    container_name: frontend
    restart: always
    ports:
      - 80:80
    command:
      - sh
      - -ce
      - |
        ENV=$(cat /fe-config.json | tr -d '\n' | tr -s ' ' | sed -e 's/ //g') envsubst < /usr/share/nginx/html/assets/env.template.js > /usr/share/nginx/html/assets/env.js                                                                        exec nginx -g 'daemon off;'
    volumes:
      - ./fe-config.json:/fe-config.json
    networks:
      - internal-log-fetcher-network
```
