### ISSUE TITLE
Helm Refactor Features: support persistence for normal nodes (and rosetta potentially?)

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#9656]
To support persistence, the generic node chart needs to mount a volume, with a configurable "name" (default = generic-node-volume),  "storageClass" (default = "standard-delete"), "Size" (default = 100Gi), and "mountPath" (default = "/data/"). If persistence is enabled, then mount this volume at the given mountPath and pass `--config-directory "{{.Values.features.persistence.mountPath}}/.mina-config"` to the daemon.

Values.yaml:
```
features:
  persistence:
    enabled: true
    storageClass: standard-delete
    mountPath: /data/
    size: 100Gi
```

Deployment:
```
        volumeMounts:
        - mountPath: {{.Values.features.persistence.mountPath}}
          name: {{.Values.features.persistence.name}}
```

VolumeClaimTemplate:
```
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{.Values.features.persistence.name}}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{.Values.features.persistence.size}}
      storageClassName: {{.Values.features.persistence.storageClass}}
      volumeMode: Filesystem
```

Statefulset:
```
{{if .Values.features.persistence.enabled}}
kind: StatefulSet
{{else}}
kind: Deployment
{{end}}
```
