### ISSUE TITLE
Helm Refactor Features: complete rosetta support

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#9657]
```
rosetta:
  enabled: false
  image:
    repository: minaprotocol/mina-rosetta-ubuntu
    pullPolicy: IfNotPresent
    tag: 1.3.0alpha2-compatible-513333d-stretch
  pg_conn: 'postgres://postgresql:5432'
  graphql_host: 'http://127.0.0.1'
```

Also add a new `.Values.port.rosetta` with the default value 3087.

This configuration should define a new template file `templates/rosetta.yaml` with similar contents to archive-node.yaml but much simpler, example starting point:
```
containers:
- image: "{{.Values.rosetta.image.repository }}:{{.Values.rosetta.image.tag}}"
  entrypoint: "mina-rosetta"
  args:
  - --archive-uri
  - {{.Values.rosetta.pg_conn | quote}}
  - --graphql-uri
  - {{.Values.rosetta.graphql_host | quote}}:{{ .Values.ports.graphql | quote }}/graphql
  - --port
  - {{.Values.port.rosetta | quote}}
```

Additional work will be required either inside the container to create a more advanced entrypoint for this specific use or additional work for a separate initContainer to set up the initial database state.

Importantly, every rosetta node relies on an archive node (and the postgres deployment that goes with it), but idk how to handle that dependency in the helm. Potentially the answer is a warning message when rosetta is enabled without archive or something, open to suggestions for how to handle this in a user-friendly way.
